export const meals = ['breakfast', 'lunch', 'dinner']
export const days = [
  'monday',
  'tuesday',
  'wednesday',
  'thursday',
  'friday',
  'saturday',
  'sunday',
]
export const ingredients = [
  '🥑 Avocado',
  '🥓 Bacon',
  '🥩 Beef',
  '🥦 Broccoli',
  '🧈 Butter',
  '🥬 Cabbage',
  '🥕 Carrot',
  '🧀 Cheese',
  '🍗 Chicken',
  '🥥 Coconut',
  '🌽 Corn',
  '🦀 Crab',
  '🥒 Cucumber',
  '🍳 Egg',
  '🍆 Eggplant',
  '🧄 Garlic',
  '🍯 Honey',
  '🍋 Lemon',
  '🦞 Lobster',
  '🍈 Melon',
  '🥛 Milk',
  '🍄 Mushroom',
  '🧅 Onion',
  '🦪 Oyster',
  '🍝 Pasta',
  '🥜 Peanuts',
  '🥔 Potato',
  '🍚 Rice',
  '🍤 Shrimp',
  '🍠 Sweet Potato',
  '🍅 Tomato',
]
